export const jobs =[
  {   jobId: '11222', 
      company: 'abcs',
      title: 'Set',
      status: 'Sez',
      location: 'Sel',
      salary: 'Sesa',
      post_url: 'Seurl',
      description: 'Sed',
      notes: 'Sen',
      color: 'Seco',

  },
   {  jobId: '22',
      company: 'abcs1',
      title: 'Set1',
      status: 'Sez1',
      location: 'Sel1',
      salary: 'Sesa1',
      post_url: 'Seurl1',
      description: 'Sed1',
      notes: 'Sen1',
      color: 'Seco1',

  },
   {  jobId: '33',
      company: 'abcs2',
      title: 'Set2',
      status: 'Sez2',
      location: 'Sel2',
      salary: 'Sesa2',
      post_url: 'Seurl2',
      description: 'Sed2',
      notes: 'Sen2',
      color: 'Seco2',

  }
]